### ISSUE TITLE
Scrolling through outputs with keyboard?

### ISSUE THREAD

**Issue by macromogic** [joouha/euporie#109]
Hi,

Thanks for providing the amazing tool! I am trying to use euporie on a notebook which produces long outputs. However I figured out that the keyboard command only scrolls through code cells and I have to use the mouse wheel or drag the scroll bar to view the entire output. Is it possible to enable keyboard scrolling for cell outputs in the future? Thanks!

**Comment by joouha** [comment]
Hi macromogic,

The <kbd>[</kbd> and <kbd>]</kbd> keys will scroll the notebook up and down one line at a time. 

The <kbd>{</kbd> and <kbd>}</kbd> keys will scroll the notebook up and down five lines at a time. 

You can view all keyboard shortcuts from the help menu (it looks like the list of shortcuts in the online documentation is broken - I'll fix this).

**Comment by joouha** [comment]
I've fix the documentation, you can also view a list of shortcuts here:
https://euporie.readthedocs.io/en/dev/pages/keybindings.html#interactive-notebooks

**Comment by macromogic** [comment]
Thanks! I just figured out that I should exit the cell edit mode to use these keys. Putting this message here in case anyone else has a similar question.
