### ISSUE TITLE
markdonw-it-py version conflict

### ISSUE THREAD

**Issue by konosubakonoakua** [joouha/euporie#114]
`euporie` requires `markdown-it-py~=2.1.0`, but `rich` requires `mardown-it-py>=2.2.0`.
Should we change to `mardown-it-py~=2.2.0` ?

**Comment by joouha** [comment]
Yes that's probably sensible. Would you like to raise a PR?

**Comment by konosubakonoakua** [comment]
> Yes that's probably sensible. Would you like to raise a PR?

sure. :D
