### ISSUE TITLE
kitty: unexpected terminal clipboard access causes confirmation dialog

### ISSUE THREAD

**Issue by hrdl-github** [joouha/euporie#119]
Kitty's default configuration https://github.com/kovidgoyal/kitty/blob/575538c3f976868deb3862fdf1a55262f9208228/kitty/options/definition.py#L3142 causes terminal clipboard reads such as in  https://github.com/joouha/euporie/blob/b263a2c14f5001ab897905451d300ee0cdb36ff3/euporie/core/terminal.py#L400 to trigger a confirmation dialog. I suggest making euporie's behaviour configurable, as said dialog is displayed every time euporie starts.

**Comment by joouha** [comment]
Thanks for reporting, fixed by a49c108506da282ac4ea26232c24989145d075f4

**Comment by joouha** [comment]
I've released a new version 2.8.4 with the fix
