### ISSUE TITLE
Gnome-terminal shortcuts

### ISSUE THREAD

**Issue by evan54** [joouha/euporie#13]
Do you know how to get cltr+enter and cltr+shift+enter to work in gnome-terminal?

seems I need to do something like this but not sure what I'm looking for
https://github.com/joouha/euporie#key-remapping

I confirmed that all three enter, cltr+enter and shift+cltr+enter return the same thing by running showkey -a and they all return ^M or the 0x0d which is the \r character

**Comment by joouha** [comment]
Hi

I'm afraid I can't find a way to do this in gnome-terminal. You can use `Ctrl+r` to run cells instead.

**Comment by evan54** [comment]
cool that worked instead of ctrl+enter, any idea how to get cltr+shift+enter?

**Comment by joouha** [comment]
I've added this in `0.1.12`. I've made the fallback shortcuts match those used in `nbterm` for consistency, so if you update to `0.1.12` you can use the following:

|              Key Binding | Command                       |
| -----------------------: | :---------------------------- |
| `ctrl-e` | Run cell                  |
| `ctrl-r` | Run then select next cell |
