### ISSUE TITLE
Plots with matplotlib

### ISSUE THREAD

**Issue by volkerkarle** [joouha/euporie#19]
Dear developers,

Somehow I experience this bug that the plot turns black once I move around to other cells. I saw that you were using matplotlib as well in your examples, did you have a certain configuration for your gui?

Best,

v.

**Comment by joouha** [comment]
Hi,

Are you using kitty terminal by any chance?

The kitty image implementation is a work in progress and needs some work - I wrote a bit more about it in this [issue 12](https://github.com/joouha/euporie/issues/12#issuecomment-845989388).

**Comment by joouha** [comment]
Quick update - the kitty graphics system has been entirely re-written, so this should be fixed in the v1.0.0
