### ISSUE TITLE
jupyter-client >= 6.2.0

### ISSUE THREAD

**Issue by davidbrochart** [joouha/euporie#2]
Awesome project!
I see you require `jupyter-client>=6.2.0`, but the latest working version is `6.1.12` (`6.1.13` and `6.2.0` were yanked).

**Comment by joouha** [comment]
Thanks!

Interestingly, when running `poetry add jupyter-client` it selects 6.2.0, so it seems like poetry might be ignoring yanked packages when resolving dependencies.

What happened with `6.1.13 ` and `6.2.0`?

Are there plans for a new release with `_async_execute_interactive` or equivalent any time soon? Or am I better off working with `6.1.12` for the time being?

**Comment by davidbrochart** [comment]
> What happened with `6.1.13 ` and `6.2.0`?

They caused issues in downstream packages and we realized we needed a major release because of a breaking API.

> Are there plans for a new release with `_async_execute_interactive` or equivalent any time soon? Or am I better off working with `6.1.12` for the time being?

jupyter_client 7.0 should be released in the coming weeks.

**Comment by joouha** [comment]
I've temporary fix to make euporie work with `jupyter-client==6.1.12` (pending the release of 7.0), so I'll close this issue.
