### ISSUE TITLE
Recover deleted cells

### ISSUE THREAD

**Issue by Minyus** [joouha/euporie#22]
Thank you for this awesome tool!
I love the Vim-like keybindings of Euporie.

While using Euporie, I sometimes mistakenly delete cells, but could not find a way to recover.

It would be great if Euporie has "Undo Delete Cells" feature similar to Jupyter.

Alternatively, it would be also helpful to have an option to back up the deleted cells in the tmp directory (e.g. `/tmp/euporie_deleted_cell_2022-12-30T23:59:59.py`) so that users can recover later.

**Comment by joouha** [comment]
Hello,

I'm glad you like euporie!

This has been on my to-do list for a while - I should be able to work on it in the next week week or two.

**Comment by Minyus** [comment]
Thank you! I look forward to it.

**Comment by joouha** [comment]
This is now implemented in `v2.0.0`. You can press <kbd>z</kbd> to un-delete a cell.

**Comment by Minyus** [comment]
Worked in v2.0.1! Thanks @joouha !
