### ISSUE TITLE
Euporie fails to open notebook files with pandas dataframe HTML in cell output

### ISSUE THREAD

**Issue by Minyus** [joouha/euporie#23]
## Issue
I noticed that Euporie fails to open notebook files with pandas dataframe HTML in a cell output.

## Reproducing steps:

1. Prepare Python 3.8 environment with pandas (e.g. 1.3.3)
3. Install euporie version 1.6.2.
```bash
pip install euporie==1.6.2
```
4. Create and open a new notebook.
```bash
euporie foobar.ipynb
```
5. Run a code cell which outputs a pandas dataframe HTML.
```python
import pandas as pd

pd.DataFrame()
```
6. Save and close the notebook.
7. Try opening the notebook, but fails to open after several seconds without any errors.
```bash
euporie foobar.ipynb
```
8. [Workaround] After removing the output from the notebook file, it can be opened by Euporie.
```bash
jupyter nbconvert --clear-output --inplace foobar.ipynb
```

**Comment by joouha** [comment]
I haven't been able to reproduce this - can you post the output of `pip freeze`?

**Comment by joouha** [comment]
Also, what operating system & terminal are you using?

**Comment by Minyus** [comment]
I use Wezterm in macOS.
I tried creating a new Conda environment with the same Python packages, but the symptom did not reproduce, so let me close this issue.
Thanks.
