### ISSUE TITLE
License

### ISSUE THREAD

**Issue by davidbrochart** [joouha/euporie#3]
Any chance you can change the license to MIT or BSD?

**Comment by joouha** [comment]
I might consider this - what's your reason for asking?

**Comment by fperez** [comment]
First, thanks @joouha for this great tool! Just to add my two cents to this topic: obviously it's entirely your right to choose your license :) But I wanted to note that in general, the scientific Python/Jupyter ecosystem has settled on BSD (and similar) licenses overall. This happened organically over the years, following the lead of Python itself which is not GPL, but some of the reasoning behind it is well captured in [this message from the creator of matplotlib, John Hunter, written back in 2004](http://nipy.sourceforge.net/software/license/johns_bsd_pitch.html).

In general, if you relicense your code to be compatible with the rest of Jupyter, it will be easier to connect with the rest of the project, potentially reuse/integrate pieces of euporie elsewhere, etc.

You're 100% within your rights to keep it GPL if that is your preference, but that means the rest of Jupyter can't really use your code (Jupyter users, myself included, will obviously enjoy your contributions!) in any part of Jupyter, as we are not going to relicense all of Jupyter to GPL ever.

I hope this helps, and regardless of your decision, many thanks for this great contribution!

**Comment by joouha** [comment]
Thanks for your message @fperez - your explanation certainly helps!

I'll admit I hadn't given as much thought to licensing as I probably should have. I think your point about being able to integrate more easily with the rest of the Jupyter ecosystem is compelling, and John Hunter's essay is certainly a very interesting and thought provoking read.

I've re-licensed euporie under the MIT license \:\-\)

(Closed by 67f29423eef2d13ce8dbe32e808109ea50f76ffb)
