### ISSUE TITLE
Close the menu?

### ISSUE THREAD

**Issue by raffaem** [joouha/euporie#37]
It may be me, but I think \<Escape\> should close an open menu?

Instead only \<Tab\> seems to do the job.

Is this intended?

**Comment by joouha** [comment]
Not really intentional - I agree that <kbd>Esc</kbd> should close the menu.

I'll add this to my to-do list :-)

**Comment by joouha** [comment]
Fixed by d857da2824fe01cf835f80f85f5da371ffaf59e5 - this will be in the next release.
