### ISSUE TITLE
Images not displaying in console but do in notebook

### ISSUE THREAD

**Issue by cnrrobertson** [joouha/euporie#39]
Hi, thanks for sharing this incredible project. I've just started using the console and am having trouble getting images to display from `matplotlib`.

I'm using WezTerm and from running `console` with logging, the images are being rendered with `chafa`. In `euporie notebook` everything is working great. But in `euporie console`, the same commands yield only a blank space.

I've tried using a couple of other terminals and found that Kitty has the same issue while Gnome terminal or Gnome console works (with inferior rendering of course). 

Let me know if there is any additional information I can provide for this.

**Comment by joouha** [comment]
Hi - thank you for reporting this.

I'm experiencing the same issue - it looks like this bug which I accidentally introduced in `v2.0.7`.

I've implemented a fix (7304685b3199f595b9d8caae71d11b85a6efd3e4) and made a new release (`v2.0.9`) which includes this fix.

Could you check if `v2.0.9` fixes the issue for you?

Thanks

**Comment by cnrrobertson** [comment]
Checked and it now works with both kitty and wezterm. Thanks for the quick fix!
