### ISSUE TITLE
[Q] Any ideas on how hard it is to display images in TUI emacs via the Kitty protocol?

### ISSUE THREAD

**Issue by NightMachinary** [joouha/euporie#4]
I have been wondering about this for some time, but I had not seen anyone who knows enough elisp and Kitty to ask.

**Comment by NightMachinary** [comment]
When I try using `kitty +kitten icat ...` in the various terminals of emacs (`eshell`, `vterm`), Kitty says the terminal is unsupported. Even something as basic as just showing a single image file instead of
![image](https://user-images.githubusercontent.com/36224762/117575676-18d62f00-b0f8-11eb-8d4d-329273fab2de.png)

would be improve my QoL a lot.

**Comment by joouha** [comment]
I'm really not sure I'm afraid - I don't use emacs.

Basically, you'll need to get emacs to send the kitty graphics protocol escape sequences to stdin, along with the image data in base64 encoded chunks.

Have a read of this page, which describes the kitty image protocol:
https://sw.kovidgoyal.net/kitty/graphics-protocol.html

Hopefully this points you in the right direction - good luck!
