### ISSUE TITLE
Refresh notebook

### ISSUE THREAD

**Issue by 875d** [joouha/euporie#41]
Would it be possible to implement (1) a menu entry that refresh the notebook (i.e. reload it from file) and (2) a feature that continuously monitor the notebook file for changes, and if there are changes, automatically reload it?

The use case is: I edit the notebook in plain vim with the percentage format, and then convert it back to notebook format with jupytext.

I know euporie has vim keybindings, but I have a whole ecosystem in vim which goes beyond keybindings (custom keybindings, plugins, etc.), so I would like to edit the notebook in plain vim, and update it with jupytext.

It would be great if euporie could refresh the notebook automatically.

**Comment by joouha** [comment]
Hi, 

The first item (a command to reload the notebook file) should be pretty easy to implement. I'll try add this to the next release. Euporie's command system means you'll be able to add a [custom key-binding](https://euporie.readthedocs.io/en/latest/pages/keybindings.html#custom-key-bindings) for this too.

The continuous file monitoring could be a bit more complex, but it looks like [watchdog](https://github.com/gorakhargosh/watchdog/) might work well for this.

**Comment by 875d** [comment]
oh, thanks!

**Comment by joouha** [comment]
I've released v2.1.3, which contains the `reset-tab` command.

**Comment by 875d** [comment]
It doesn't work :(

see the video: https://www.youtube.com/watch?v=syYEL69Z98U

**Comment by 875d** [comment]
please watch it until the end as the first time the cell is hidden and it's not clear it's not working :)

**Comment by joouha** [comment]
Ah I see, thanks for the video. Please try the fix in `v2.1.4`

**Comment by 875d** [comment]
it works!!!
it doesn't keep output cells when you refresh.
for me that's the intended behavior, I don't know for others.
maybe the fact that it doesn't keep output cells when refreshed should be documented.
It is so much faster than Jupyter notebook.
Now I just have to find the command line to tell kitty to update it, and then I bind it in vim.
Thanks a lot!

**Comment by 875d** [comment]
![output](https://user-images.githubusercontent.com/118444583/204564525-61b7d6d7-521a-4503-a4c1-6f29bf112412.gif)
