### ISSUE TITLE
Cannot go left!

### ISSUE THREAD

**Issue by 875d** [joouha/euporie#43]
If I shift the cells to the right, then I cannot shift back to the left :(

See the video: https://youtu.be/VG_nabBuiew

**Comment by joouha** [comment]
Hi,

I'm not sure why this has stopped working (it definitely used to!), but I've made a fix in `v2.1.5` so it should be working again.

Any problems let me know.

**Comment by 875d** [comment]
It is better now, but if you have a long line, and you scroll right until the end, it will allow you to scroll left, but only up to a certain point, not until the start.

This is the easiest way to reproduce it. It randomly gets "stuck" but is non reproducible.

**Comment by joouha** [comment]
Thanks, I've figured out why it broken in the first place now.

I've attempted another fix in the `dev` branch (aea54ca27491d32107a670acf13bcc132a3e52be), which I'll release soon.

**Comment by joouha** [comment]
This should now be fixed in `v2.2.0`
