### ISSUE TITLE
question: sample config file for different kernel

### ISSUE THREAD

**Issue by azinsharaf** [joouha/euporie#46]
Hi, Can someone give me a config file example for ```euporie notebook``` for non-default kernel name and kernel connection file? I am using it on Windows and can't connect to an existing kernel in a python venv.

```
C:\Users\asharaf>jupyter kernelspec list
Available kernels:
  python3    C:\Users\asharaf\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\share\jupyter\kernels\python3
  xpython    C:\Users\asharaf\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone\share\jupyter\kernels\xpython
```

**Comment by 875d** [comment]
Are you talking about the `--kernel-connection-file` switch?

**Comment by joouha** [comment]
> **Warning**
> Just to warn you, this feature is pretty experimental at the moment, and it still needs a fair amount of work!

To connect to an existing kernel with euporie, you can do the following:

1. Launch an existing kernel, e.g.:

   ```bash
   jupyter-console -f=/tmp/kernel-connection-file.json --kernel=pypy3
   ```

2. Connect the existing kernel using euporie e.g.:

   ```bash
   euporie-console --kernel-connection-file=/tmp/kernel-connection-file.json --kernel-name=pypy3
   ```

   (There is currently a bug in euporie where the name of a non-default kernel will not be displayed correctly unless you specify the kernel name.)

3. You should now be able to use the kernel in both clients.
   
   All kernel outputs will be displayed regardless of which client generated them. In a notebook, outputs from other clients will be attached to the currently selected cell.

This video demonstrates this: 

https://user-images.githubusercontent.com/12154190/205264167-d4a531a1-2125-49cc-9f0f-2313570faed6.mp4

I haven't tried this on Windows yet, but I imagine it should work in the same way.

**Comment by 875d** [comment]
wow!

**Comment by azinsharaf** [comment]
@875d & @joouha 
Thanks. I need the content of `kernel-connection-file.json` file.

**Comment by azinsharaf** [comment]
thanks @joouha. It created the config file so i close this issue. The euporie doesn't work with my python setup in Windows so I may ask that question in a separate post to see if it is doable to use it or not.
