### ISSUE TITLE
Remove shadow

### ISSUE THREAD

**Issue by 875d** [joouha/euporie#47]
Please, how can I remove the shadow?

![2022-12-02-083654_hyprshot](https://user-images.githubusercontent.com/118444583/205241689-93402e8e-dfe6-4e4e-a864-2f6726ec1c6e.png)

**Comment by joouha** [comment]
I've added this in b238a906bebe67a90121843886a24ec648b1b875, it'll be possible in the next release :-)

**Comment by 875d** [comment]
thank you very much :)
