### ISSUE TITLE
light mode

### ISSUE THREAD

**Issue by 54696d21** [joouha/euporie#5]
do you plan on adding a mode for light background terminals?

**Comment by joouha** [comment]
It should be usable on light background terminals as is - is there anything specific that wasn't working?

I tried to pick a default syntax highlighting theme which is readable on both light and dark terminals, but it's possible that it might not work with certain colour-schemes.

I'll be adding a configuration file soon which will allow you to change the colour scheme.

**Comment by 54696d21** [comment]
in my terminal the font is light grey against a white background

**Comment by joouha** [comment]
In [v0.1.4](https://github.com/joouha/euporie/releases/tag/v0.1.4) I've changed the default syntax highlighting theme to `default`, which looks OK on both light and dark terminals.

I've also added the ability to change the syntax highlighting theme (but be aware that setting are not saved yet).

![image](https://user-images.githubusercontent.com/12154190/117694005-88aaef00-b1b6-11eb-83d4-fef668ac34b5.png)
