### ISSUE TITLE
image rendering on alacritty

### ISSUE THREAD

**Issue by azinsharaf** [joouha/euporie#51]
Is it a known limitation in Alacritty terminal that can't render the images well?

I don't know anything about `sixel` and not sure if is usable on Windows. I installed `timg` in my python env and it broke it. 

![image](https://user-images.githubusercontent.com/10101468/205999076-31313fcd-32b4-4235-b923-9300220f809b.png)

**Comment by joouha** [comment]
Hello,

Alacrity does not support terminal graphics (yet - https://github.com/alacritty/alacritty/pull/4763).

I've struggled to get terminal graphics support working using Windows-native Python. I've not found anything which works perfectly yet.

You can try [wezterm](https://wezfurlong.org/wezterm/), but it has issues with graphics on Windows (see https://github.com/wez/wezterm/issues/1236, https://github.com/wez/wezterm/issues/2422).

Alternatively you could give [mintty](https://mintty.github.io/) a try, which also supports sixels on Windows.

Let me know if you find a solution that works!

**Comment by azinsharaf** [comment]
Thanks for the info. I tried it quickly in WSL (IUbuntu ) and got the same result. Are you saying it should work in Linux? I'll be testing it again later.

**Comment by joouha** [comment]
Yep, I've tested euporie using [wsltty](https://github.com/mintty/wsltty) (which uses mintty) and terminal graphics work.
