### ISSUE TITLE
can't indent

### ISSUE THREAD

**Issue by atobi16** [joouha/euporie#59]
I'm working with the mac default terminal, iterm2 I think.
Pressing tab in a cell brings up autocomplete, but I need to indent instead.
How would I go about this?

**Comment by atobi16** [comment]
Is there a way to use vi bindings and still be able to indent in insert mode?

**Comment by joouha** [comment]
Not currently, but I'll look into adding this.

**Comment by luisbc92** [comment]
It would be amazing to have this feature, it's pretty annoying not to be able to use Tab to indent.

**Comment by joouha** [comment]
Implemented in b5e59470782b2adf197a997a47a5c0264d0a8d96

**Comment by luisbc92** [comment]
Awesome! Thank you for implementing this feature.

**Comment by joouha** [comment]
This is now released in `v2.8.4`
