### ISSUE TITLE
How to connect to hub

### ISSUE THREAD

**Issue by puppyapple** [joouha/euporie#62]
After launching a hub in a remote machine, how to connect to the hub locally? I have tried write a config file with ip and port settings, by  [euporie-notebook -f=myconfig.json], nothing happens.

**Comment by joouha** [comment]
Hi,

Euporie hub runs as an SSH server, so you shoild be able to connect to the remote machine on the configured port using any SSH client.

**Comment by puppyapple** [comment]
@joouha thanks for the reply! So you mean run hub as a server and use ssh to connect to it. I tried [ssh -p xxxx user@myhost] and in the remote server console I received error like ['Vt100Parser' object has no attribute 'queries']. I think the connection works but some other issues comed out?
<img width="717" alt="image" src="https://user-images.githubusercontent.com/33118185/218310093-8f9c7a39-6915-4b0f-abc0-f84448e8a110.png">

**Comment by puppyapple** [comment]
And in fact, what I'm really looking for, is that I could launch euporie-notebook with a .ipynb file locally and select a kernel from a remote server(usually has more powerful cpu and gpu capabilities)

**Comment by joouha** [comment]
Ah - that `AtrributeError` looks like a bug. I'll take a look at it when I next can.

It should be possible to connect to a remote kernel over SSH using euporie, but it'd be a bit involved. You'd need to run your kernel on the remote server, forward the ports that the kernel is listening on to the local machine, then provide a connection file to euporie (using the [`--kernel-connection-file`](https://euporie.readthedocs.io/en/latest/apps/notebook.html#cmdoption-kernel-connection-file) command line option). [This article](https://mazzine.medium.com/how-to-connect-your-spyder-ide-to-an-external-ipython-kernel-with-ssh-putty-tunnel-e1c679e44154) gives a good idea of what would be involved. I haven't tried this though, so there are no guarentees!

However, since euporie is designed to run in the terminal, it would be far simpler to connect to the server using SSH and run euporie there (this is one of euporie's intended use-cases 🙂).

**Comment by puppyapple** [comment]
@joouha Thank you for the tip! I will give it a try~🙂

**Comment by puppyapple** [comment]
> Ah - that `AtrributeError` looks like a bug. I'll take a look at it when I next can.
> 
> It should be possible to connect to a remote kernel over SSH using euporie, but it'd be a bit involved. You'd need to run your kernel on the remote server, forward the ports that the kernel is listening on to the local machine, then provide a connection file to euporie (using the [`--kernel-connection-file`](https://euporie.readthedocs.io/en/latest/apps/notebook.html#cmdoption-kernel-connection-file) command line option). [This article](https://mazzine.medium.com/how-to-connect-your-spyder-ide-to-an-external-ipython-kernel-with-ssh-putty-tunnel-e1c679e44154) gives a good idea of what would be involved. I haven't tried this though, so there are no guarentees!
> 
> However, since euporie is designed to run in the terminal, it would be far simpler to connect to the server using SSH and run euporie there (this is one of euporie's intended use-cases 🙂).

Hi, @joouha , when I SSH to a remote server and use euporie to open jupyternotebook, the image will not show(only a "Image" text in center). But locally it works well. So is there any configuration that I missed?

**Comment by joouha** [comment]
Hi,

What terminal are you using?

It sounds like euporie might be missing a [dependency required to show images](https://euporie.readthedocs.io/en/latest/pages/installation.html#images) on your SSH server. If you are able to share the output of `pip freeze` from euporie's environment on the SSH server, that would be really useful to help me understand what's happened here.

Then make sure you have the `Pillow` and `timg` Python packages installed in the same environment as euporie. I'd also try installing `chafa.py` and seeing if that helps.

**Comment by puppyapple** [comment]
> 

Sorry for the late reply. I install euporie in the base conda env(on a remote server) in which I've ensured that Pillow, timg and chafa.py are installed. Here is my pip freeze result.
[freeze.txt](https://github.com/joouha/euporie/files/11189575/freeze.txt)

**Comment by puppyapple** [comment]
and btw, how could I have [In] and [Out] style view(input cell output cell seperately) like what's shown in you video. I failed to find the correct config. Thanks!

**Comment by joouha** [comment]
> I install euporie in the base conda env(on a remote server) in which I've ensured that Pillow, timg and chafa.py are installed.

Were images working over SSH after this? With the packages installed in your pip-freeze output I'd expect images to be displaying.

> how could I have [In] and [Out] style view(input cell output cell seperately) like what's shown in you video

Do you mean [the video here](https://euporie.readthedocs.io/en/latest/apps/console.html)? If so, this is `euporie-console`, which is a REPL console that connects to Jupyter kernels. You can run `euporie-console` to run it.

**Comment by puppyapple** [comment]
> Were images working over SSH after this? With the packages installed in your pip-freeze output I'd expect images to be displaying.
Unfortunately no, there is still "Image" text in center(I even tried with a new conda environment with all package reinstalled from start, still not working)

**Comment by puppyapple** [comment]
> What terminal are you using

Kitty terminal(the icat command works normaly over SSH)

**Comment by joouha** [comment]
This is now possible in the latest `dev` branch by using the `--force-graphics` option, implemented in 49a2c4e508f0dd7f1526f8c1d3c5f0e73c1b7b98
