### ISSUE TITLE
Xonsh support

### ISSUE THREAD

**Issue by anki-code** [joouha/euporie#63]
Hi! Thank you for the awesome tool!
Is there a way to use [xonsh shell](https://xon.sh) language in the cells?
Thanks!

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by joouha** [comment]
Hi,

This should "just work" by installing xonsh's [Jupyter kernel](https://github.com/xonsh/xontrib-jupyter) and [selecting the "xonsh" kernel in euporie](https://euporie.readthedocs.io/en/latest/apps/notebook.html#changing-the-kernel).

However, it looks like there is currently an unresolved [bug in the xonsh kernel](https://github.com/xonsh/xontrib-jupyter/issues/6) which prevents it from working properly in the latest version of xonsh.

**Comment by joouha** [comment]
I've made a new release `v2.3.2` which has all the fixes mentioned above.

With the fixes to `xontrib-jupyter-shell`, xonsh now works really nicely in euporie 🏆
