### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by anki-code** [joouha/euporie#64]
Hello! Thank you for the awesome tool!
Just want to let you know that on Mac with iTerm2 or standard Terminal the combinations around `<Any key>+Enter` are not working.
The one way to run code on Mac is to switch to Vi mode and press Enter.
It will be cool to fix some day.
Thanks!

**Comment by joouha** [comment]
Euporie uses the CSI-u terminal mode to recognise these key-sequences (which traditionally is not possible on a vt100 terminal).

I'm not sure that the standard MacOS terminal supports CSI-u, so you'll probably have to use the <kbd>Ctrl + e</kbd> and <kbd>Ctrl + r</kbd> key-bindings instead.

iTerm2 does support CSI-u key-bindings, but I believe you have to enable them in the settings:

<img src="https://github.com/tmux/tmux/wiki/images/iterm2_csi_u.png" width=292>

There are instructions for other terminals in [euporie's documentation here](https://euporie.readthedocs.io/en/latest/pages/keybindings.html#running-cells).

I've recently made some changes in the `dev` branch which might help with this, and terminal configuration unnecessary for some terminals - see https://github.com/joouha/euporie/issues/61.
