### ISSUE TITLE
[Feature Request] Load percent python scripts as Notebook

### ISSUE THREAD

**Issue by danielcs88** [joouha/euporie#68]
Eupories is an amazing alternative to load Jupyter Notebooks. It would be amazing if there was a way to load as notebooks files that have cells in percent format, e.g.:

```python
# %% [markdown]
# # Example

# %%
import pandas as pd

# %%
df = pd.DataFrame({"A": [1, 2, 3, 4]})
```

**Comment by joouha** [comment]
I've got this working locally - `jupytext` makes this very easy to implement.

I just need to add some interface which allows you to choose whether to open text files as notebooks or text files, and to choose whether to save notebooks as notebooks or text files.

This should make it into the next release.
