### ISSUE TITLE
Inconsistency of `typing-extensions` and `platformdirs` in the dependencies

### ISSUE THREAD

**Issue by jan-janssen** [joouha/euporie#76]
`platformdirs` 3.5 has the dependency `typing-extensions>=4.5`: 
https://github.com/platformdirs/platformdirs/blob/3.5.0/pyproject.toml#L49

But `euporie` has the dependencies `platformdirs~=3.5` and `typing-extensions~=4.2`. These dependencies are incompatible.

**Comment by joouha** [comment]
Thanks for reporting this.

I've made a new patch release with `typing-extensions~=4.5`
