### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by raffaem** [joouha/euporie#82]
1. The last version on PyPi is [2.4.3](https://pypi.org/project/euporie/#history)
2. The last commit says "Release 2.4.2". Where did 2.4.3 pop out from?

![image](https://github.com/joouha/euporie/assets/54762742/07b8ef23-84d3-4d4e-80fb-2bddf2f81940)

3.The [ChangeLog](https://euporie.readthedocs.io/en/latest/pages/changelog.html) lists two 2.4.2 releases:

![image](https://github.com/joouha/euporie/assets/54762742/1fa09b06-946a-43d2-9596-8555ccf06608)

4. GitHub's last release is 2.4.0

![image](https://github.com/joouha/euporie/assets/54762742/ef14fcfd-6226-4a20-8283-b71f607c0824)

**Comment by joouha** [comment]
Haha what a mess 😳

The latest commit is a typo - it should have said "Release v2.4.3".

The latest version in the changelog is also a typo!

I've been adding the github releases manually, and must have forgotten for the last couple of versions.

I'll sort it out.

**Comment by joouha** [comment]
> The last commit says "Release 2.4.2". Where did 2.4.3 pop out from?

IF you check the `main` branch you will see commit 49c8722c7e71b34b198177b6464d7522c0a649f4, which is where `v2.4.3` is released.

**Comment by joouha** [comment]
This should be fixed now :-)
