### ISSUE TITLE
Menu access in kitty

### ISSUE THREAD

**Issue by raffaem** [joouha/euporie#83]
I'm using `euporie-notebook` but I don't know how to access the menu bar. I thought it was ALT+F (for the file menu) but that doesn't work.

Is this documented? Because I looked in the "Keybindings" section of the docs and couldn't find it

**Comment by joouha** [comment]
<kbd><kbd>Alt</kbd>+<kbd>f</kbd></kbd> should open the file menu - which terminal are you using?

You can also press <kbd>F10</kbd> to open the menu, or you can click on the menu with the mouse.

I seem to have missed the menu interaction shortcuts from the docs - I'll add them.

**Comment by raffaem** [comment]
> Alt+f should open the file menu - which terminal are you using?
> 
> You can also press F10 to open the menu, or you can click on the menu with the mouse.
> 
> I seem to have missed the menu interaction shortcuts from the docs - I'll add them.

Alt+f does not work to open the menu. I'm using kitty.

F10 works and always open the file menu

**Comment by raffaem** [comment]
It works in Konsole, so it seems there's something wrong in my kitty

**Comment by raffaem** [comment]
ok thanks

**Comment by raffaem** [comment]
Any news on this?

**Comment by joouha** [comment]
Hi - yes, this should be fixed by 3be89a4d0a5d4fca8689c73ceeed5985b64f62b4 in the `dev` branch

**Comment by raffaem** [comment]
It works wonderfully. Thanks!
