### ISSUE TITLE
Sync state of notebook when changed from outside of euporie

### ISSUE THREAD

**Issue by IndianBoy42** [joouha/euporie#84]
Hey! I am hoping to use euporie as a in terminal solution for running and displaying notebooks, but editing it from within neovim using jupytext.vim. Right now the problem is that editing from neovim doesn't show the changes in euporie. Autoreading would be nice but manually reloading with a keybinding works too since I can send keypresses from neovim to the terminal that euporie is running in

**Comment by joouha** [comment]
<kbd>F5</kbd>

**Comment by IndianBoy42** [comment]
Ah it does, I tried looking at the command palette but didn't find that. The hint text for it is "Reset the current tab" which is not really what i would expect for this function

**Comment by joouha** [comment]
Good point, I'll update the description
