### ISSUE TITLE
  Wrap text around

### ISSUE THREAD

**Issue by ghost** [joouha/euporie#86]
How can I wrap text around?

![image](https://github.com/joouha/euporie/assets/118444583/70c91468-e436-4e4c-8da0-37ef9b8c2bb4)

**Comment by joouha** [comment]
Hi - not currently possible, but I think it should be!

I'll see what I can do.

**Comment by joouha** [comment]
BTW, you can scroll a cell's output left and right using the <kbd>left</kbd> and <kbd>right</kbd> arrow keys when the cell is selected.
