### ISSUE TITLE
No Kernels Found Error

### ISSUE THREAD

**Issue by Ha5hBr0wn** [joouha/euporie#89]
Whenever I try to open a notebook I get a warning that looks like the image below: 
<img width="514" alt="image" src="https://github.com/joouha/euporie/assets/53263858/ff25752b-aaa3-44e0-8c5a-bb85d8c507b2">

Steps to replicate: 

install brew with curl
install pipx with brew
install euporie with pipx
pip install --user ipykernel

all of the above is done with the suggested command from my ~ dir

I also added all the suggested paths to my $PATH from each installation

How can I run code? Also I thought the whole point of pipx was to install all required packages in an isolated venv that the executable uses, so why am I even executing `pip install --user ipykernel` in the first place?

**Comment by Ha5hBr0wn** [comment]
Okay I made some progress. So it looks like to install packages for the pipx environment one has to activate the venv and then run `python -m pip install ipykernel` (not just pip install, otherwise won't install for venv)

Now when I open a notebook file the editor immediately print some error lines which disappear instantly so I can't read them and then shows the editor (I can type in it but I can't execute code, nor is the menu bar visible so I just quit by closing the entire terminal window)

**Comment by joouha** [comment]
There's quite a lot going on here!

Euporie does not pull in any Jupyter kernels as dependencies - it's a Jupyter client, but you need to install a kernel yourself. 

A Jupyter kernel does not have to be Python - there are kernels for many programming languages. `ipykernel` is a Jupyter kernel for the Python programming language. While it is technically possible to instally `ipykernel` inside your euporie pipx virtual-environment, it's almost certainly not what you want to do (you might want to uninstall it from the pipx virtual-environment). You probably want your Python kernel to be installed in your system-wide Python prefix.

You can do this by running the following (without any virtual environment activated):

```
pip install --upgrade ipykernel
```

You then need to register this `ipykernel` installation as your Python kernel of choice, which you can do by running the following:

```bash
python -m ipykernel install --user
```

Then you should be able to run code in euporie.

---

You can quit `euporie` by pressing <kbd>Ctrl + q</kbd>.

**Comment by joouha** [comment]
> Also, iterm2 also doesn't allow for any keybinding to execute cells.

<kbd>Ctrl+e</kbd> and <kbd>Ctrl+r</kbd> should work.

> Any ideas how to provide good debugging information?

If you run `euporie-notebook` with `--log-level=debug --log-file=euporie.log`, then debug info will be logged to the file `euporie.log`.

The main cause of the kernel related errors (as described in #75) should have been fixed by 3a5e39f7ccb762496c8d7f5728daf49ea5a1a213. I'll be making a new release with this pretty soon.

**Comment by joouha** [comment]
Should be fixed, please open a new issues if you're still experiencing problems with the latest version of euporie

**Comment by stevenwalton** [comment]
I faced this issue and wanted to log the solution for others. @joouha I think it could help by putting this in the README/docs. 

The problem:
```
uv tool install euporie
uv pip install ipykernel
euporie-notebook my_notebook.ipynb
# error about no kernels
```

A key missing part is the need to do `python -m ipykernel install` and a dumb user (read: "me") is going to miss this if all they do is look at the README or the [install instructions](https://euporie.readthedocs.io/en/latest/pages/installation.html). The solution is found by searching issues instead. So I think it could help others avoid the confusion I had by just adding a few lines to the docs. 

(Since this actually wants to install to somewhere like `/usr/local/share/jupyter/kernels` and you'll get a permission error, so use `sudo`).

Proposed change to README:

```rst
*******
Install
*******

You can install euporie with `uv <https://docs.astral.sh/uv/>`_  (recommended), or with `pipx <https://pipxproject.github.io/>`_ or ``pip``):

.. code-block:: console

   $ uv tool install euporie
   $ # OR
   $ pipx install euporie
   $ # OR
   $ python -m pip install --user euporie

If you have not already done so, you will need to install `ipykernel` to your system to be able to use `euporie-notebook`.

.. code-block:: console

   $ # If you haven't already done so
   $ uv pip install ipykernel
   $ # Install the kernel so we can access it
   $ sudo python3 -m ipykernel install

You can also try euporie online `here <https://mybinder.org/v2/gh/joouha/euporie-binder/HEAD?urlpath=%2Feuporie%2F>`_.
```

**Comment by joouha** [comment]
Thanks for this &nbsp; 🙏 

I'd generally recommend against using `sudo` to register the kernel, but it's up to you. You can register it just for the current user using the `--user` flag:

```bash
python -m ipykernel install --user
```

I've added a section about installing kernels to the documentation [here](https://euporie.readthedocs.io/en/dev/pages/installation.html#jupyter-kernels).

**Comment by stevenwalton** [comment]
> I'd generally recommend against using sudo to register the kernel, but it's up to you.

This is my preference, but I was having a hard time figuring it out but honestly didn't spend much time. I assume it was some overloaded environment variable because I had tried again (thanks to this message) and things worked just fine. So classic Heisenbug lol
