### ISSUE TITLE
some newbie questions

### ISSUE THREAD

**Issue by vinniec** [joouha/euporie#90]
I installed euporie on my phone today with termux, very nice but I had some questions:
1) is it really necessary to require rust as a dependency? I think it is necessary for "maturin"
2) also, since i'm using termux, i had to install pyzmq it was necessary to install "libzmq" I don't know if is needed to specify this dependency, i also specifies the variable AR=llvm-ar in the command `AR=llvm-ar pipx install euporie`, I don't remember now, however, if it was necessary
3) however, ipykernel also had to be installed likes this `pipx inject euporie ipykernel` but then I realized that libraries could not be used outside the isolated environment and I installed euporie with pip in the global system.
4) question: %load doesn't seem to work, it doesn't paste the text into the cell (however if I give a wrong Path an error is raised, so I guess there is only and error of output)

**Comment by joouha** [comment]
Hi,

1. Rust is not a dependency for euporie (it's a pure python package). It sounds like you're using termux, so I'm assuming you're on an aarch64 architecture or similar. Presumably some dependency needs rust as a build-time dependency. There are almost no pre-compiled wheels for aarch64 on PyPi, hence the need to compile packages yourself. On a typical x86_64 machine, rust is not required, as there will be prebuilt wheels available.

2. See above. Typically one specifies python packages as dependencies of your python package. If those packages need compiling, you'd have to consult the documentation for those packages to find the build-time dependencies.

3. Typically you'd want `ipykernel` installed in your global python environment and euporie isolated in a pipx managed virtual environment.

4. I haven't implemented `%load` magic - I'll treat this as a feature request :-)

**Comment by vinniec** [comment]
hey, thanks for the response.
Regarding rust, later I also installed just jupyter and that dependency was required in the same way as well as everything I specified in point 2.
So let's say they are not requirements for euporie but for jupyter, sorry for my mistake.

I also wanted to ask you one more thing, tell me if you like the idea:
I noticed that you can directly open a .py file directly in euporie however at that point it is treated as a regular text file.
However I think that used that way euporie could safely be considered a code editor if instead the file is treated as if it were inside a code cell.
Okay, maybe that's bad to say but from the perspective of using euporie on android, currently so it would be better than the vast majority of editors out there .

**Comment by joouha** [comment]
If you install `jupytext`, euporie can open python scripts as notebooks, which might do what you are after

**Comment by joouha** [comment]
I've implemented `%load` magic in `euporie-notebook` and `euporie-console` - they'll be in the next release 🪠

**Comment by vinniec** [comment]
Thanks :)
