### ISSUE TITLE
Scrolling past top in vim normal mode replaces text

### ISSUE THREAD

**Issue by arhowe00** [joouha/euporie#92]
When in normal mode within a cell, scrolling up past the top will cause text that was previously in the cell (and deleted) to replace the text that is in the cell.  

AT TOP OF CELL:
![image](https://github.com/joouha/euporie/assets/38041948/5ce38b37-95ec-4948-8a5c-fbd5105c2a03)

I PRESS 'k' AT TOP OF CELL:
![image](https://github.com/joouha/euporie/assets/38041948/71da7108-175f-475e-ad39-8269133dad86)

**Comment by joouha** [comment]
Hi,

This appears to be a bug with the vi-style key-bindings, where <kbd>k</kbd> is bound to scrolling through a text-buffer's history.

This behaviour is inherited from `prompt_toolkit`, but should have been overridden.

I'll work on a fix 👍

**Comment by joouha** [comment]
Hi - this should be fixed by 9cbf478b9828b2305e796623281ee2439c19ad14 in the `dev` branch, and will be in the next release 🧲
